name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
